name: Deploy

on:
  push:
    branches:
      - master
jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest

    steps:
    - name: connect to server
      run: ssh ${{ secrets.USER_IP }} 
    - name: update repo
      run: cd bin/mensabot_lg && git checkout master && git pull && exit
    - name: cleanup
      run: rm -rf ~/.ssh
